export interface Country {
  code: string;
  name: string;
  cities: string[];
}

export const COUNTRIES: Country[] = [
  { code: 'US', name: 'United States', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'Miami', 'Seattle', 'Boston', 'Washington DC', 'Philadelphia', 'Dallas', 'Denver', 'Atlanta', 'Portland', 'Minneapolis', 'Detroit', 'New Orleans', 'Austin', 'Nashville', 'Pittsburgh'] },
  { code: 'GB', name: 'United Kingdom', cities: ['London', 'Manchester', 'Birmingham', 'Glasgow', 'Edinburgh', 'Liverpool', 'Bristol', 'Leeds', 'Sheffield', 'Oxford', 'Cambridge', 'Brighton', 'Newcastle', 'Nottingham', 'Cardiff'] },
  { code: 'FR', name: 'France', cities: ['Paris', 'Lyon', 'Marseille', 'Bordeaux', 'Toulouse', 'Nantes', 'Strasbourg', 'Lille', 'Nice', 'Rennes', 'Montpellier', 'Grenoble'] },
  { code: 'DE', name: 'Germany', cities: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dresden', 'Nuremberg', 'Mannheim', 'Bremen'] },
  { code: 'IT', name: 'Italy', cities: ['Rome', 'Milan', 'Florence', 'Venice', 'Naples', 'Turin', 'Bologna', 'Genoa', 'Palermo', 'Verona', 'Bari', 'Catania'] },
  { code: 'ES', name: 'Spain', cities: ['Madrid', 'Barcelona', 'Seville', 'Valencia', 'Bilbao', 'Granada', 'Málaga', 'Zaragoza', 'Murcia', 'Valladolid', 'Alicante'] },
  { code: 'NL', name: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Tilburg', 'Almere'] },
  { code: 'JP', name: 'Japan', cities: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Fukuoka', 'Sapporo', 'Kobe', 'Hiroshima', 'Sendai'] },
  { code: 'CN', name: 'China', cities: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xi\'an', 'Chongqing', 'Nanjing'] },
  { code: 'KR', name: 'South Korea', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Gwangju', 'Daejeon'] },
  { code: 'AU', name: 'Australia', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Hobart', 'Darwin'] },
  { code: 'CA', name: 'Canada', cities: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Quebec City', 'Winnipeg', 'Victoria', 'Halifax'] },
  { code: 'BR', name: 'Brazil', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Curitiba', 'Porto Alegre', 'Recife', 'Manaus'] },
  { code: 'MX', name: 'Mexico', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Oaxaca', 'Mérida', 'León', 'San Miguel de Allende'] },
  { code: 'AR', name: 'Argentina', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata', 'Tucumán'] },
  { code: 'CH', name: 'Switzerland', cities: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'] },
  { code: 'AT', name: 'Austria', cities: ['Vienna', 'Graz', 'Salzburg', 'Innsbruck', 'Linz'] },
  { code: 'BE', name: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liège'] },
  { code: 'PT', name: 'Portugal', cities: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Faro'] },
  { code: 'PL', name: 'Poland', cities: ['Warsaw', 'Kraków', 'Wrocław', 'Gdańsk', 'Poznan', 'Łódź'] },
  { code: 'CZ', name: 'Czech Republic', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň'] },
  { code: 'HU', name: 'Hungary', cities: ['Budapest', 'Debrecen', 'Pécs', 'Győr'] },
  { code: 'RO', name: 'Romania', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța'] },
  { code: 'GR', name: 'Greece', cities: ['Athens', 'Thessaloniki', 'Heraklion', 'Patras'] },
  { code: 'SE', name: 'Sweden', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping'] },
  { code: 'NO', name: 'Norway', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'] },
  { code: 'DK', name: 'Denmark', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'] },
  { code: 'FI', name: 'Finland', cities: ['Helsinki', 'Tampere', 'Turku', 'Oulu'] },
  { code: 'RU', name: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan'] },
  { code: 'TR', name: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Antalya', 'Bursa'] },
  { code: 'IN', name: 'India', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune', 'Ahmedabad', 'Jaipur', 'Kochi'] },
  { code: 'SG', name: 'Singapore', cities: ['Singapore'] },
  { code: 'HK', name: 'Hong Kong', cities: ['Hong Kong'] },
  { code: 'TW', name: 'Taiwan', cities: ['Taipei', 'Kaohsiung', 'Taichung'] },
  { code: 'ZA', name: 'South Africa', cities: ['Cape Town', 'Johannesburg', 'Durban', 'Pretoria'] },
  { code: 'NG', name: 'Nigeria', cities: ['Lagos', 'Abuja', 'Ibadan', 'Kano'] },
  { code: 'EG', name: 'Egypt', cities: ['Cairo', 'Alexandria', 'Luxor', 'Aswan'] },
  { code: 'MA', name: 'Morocco', cities: ['Marrakech', 'Casablanca', 'Rabat', 'Fez', 'Tangier'] },
  { code: 'IL', name: 'Israel', cities: ['Tel Aviv', 'Jerusalem', 'Haifa'] },
  { code: 'AE', name: 'United Arab Emirates', cities: ['Dubai', 'Abu Dhabi', 'Sharjah'] },
  { code: 'NZ', name: 'New Zealand', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'] },
  { code: 'IE', name: 'Ireland', cities: ['Dublin', 'Cork', 'Galway', 'Limerick'] },
  { code: 'HR', name: 'Croatia', cities: ['Zagreb', 'Split', 'Dubrovnik', 'Rijeka'] },
  { code: 'SK', name: 'Slovakia', cities: ['Bratislava', 'Košice'] },
  { code: 'SI', name: 'Slovenia', cities: ['Ljubljana'] },
  { code: 'RS', name: 'Serbia', cities: ['Belgrade', 'Novi Sad'] },
  { code: 'UA', name: 'Ukraine', cities: ['Kyiv', 'Lviv', 'Kharkiv', 'Odesa'] },
  { code: 'CL', name: 'Chile', cities: ['Santiago', 'Valparaíso', 'Concepción'] },
  { code: 'CO', name: 'Colombia', cities: ['Bogotá', 'Medellín', 'Cali', 'Cartagena'] },
  { code: 'PE', name: 'Peru', cities: ['Lima', 'Cusco', 'Arequipa'] },
  { code: 'TH', name: 'Thailand', cities: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya'] },
  { code: 'ID', name: 'Indonesia', cities: ['Jakarta', 'Bali', 'Bandung', 'Yogyakarta', 'Surabaya'] },
  { code: 'MY', name: 'Malaysia', cities: ['Kuala Lumpur', 'George Town', 'Johor Bahru'] },
  { code: 'PH', name: 'Philippines', cities: ['Manila', 'Cebu', 'Davao'] },
  { code: 'VN', name: 'Vietnam', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hội An'] },
];
